# Generated by Django 3.2.4 on 2021-06-18 07:42

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.FileField(upload_to='', validators=[blog.validators.validate_file_extension]),
        ),
    ]
