# Generated by Django 3.2.4 on 2021-06-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
